name: MarioPlugIn
version: ${project.version}
main: de.mariocst.MarioMain
api-version: 1.16
authors: [ marioCST ]
description: marioCSTs 1.16.5 PlugIn

commands:
  heal:
    description: Dieser Command heilt dich.
    aliases: ["healme", "h"]
    permission: mario.heal
  date:
    description: Zeigt das Datum an.
    permission: mario.date
  lol:
    description: Schreibt lol.
    permission: mario.lol
  announcerestart:
    description: ADMIN Schreibt 5mal in den Chat "SERVER RESTART! Bitte in 1 Min. wieder joinen!".
    aliases: ["ars"]
    permission: mario.restart
  announcestop:
    description: ADMIN Schreibt 5mal in den Chat "SERVER STOPP! Danke für's spielen!".
    aliases: ["as"]
    permission: mario.stop
  announcereload:
    description: ADMIN Schreibt 5mal in den Chat "SERVER RELOAD! Bitte keine Befehle eingeben!".
    aliases: ["arl"]
    permission: mario.reload
  announcekick:
    description: ADMIN Schreibt 5mal in den Chat "ALLE WERDEN GEKICKT! BITTE NACH KURZER ZEIT REJOINEN! NICHT DIREKT".
    aliases: ["ak"]
    permission: mario.kick
  die:
    description: Lässt dich sterben.
    aliases: ["dead"]
    permission: mario.die
  broadcast:
    description: ADMIN Schreibt die Nachricht nach dem Befehl in den Chat!
    aliases: ["bc"]
    permission: mario.broadcast
  broadcast5:
    description: ADMIN Schreibt die Nachricht nach dem Befehl 5 Mal in den Chat!
    aliases: ["bc5"]
    permission: mario.broadcast5
  discord:
    description: Link zum definierten Discord. (MUSS IMMER MIT /setlink NACH JEDEM RESTART/RELOAD/STOP NEU DEFINIERT WERDEN!!!!)
    aliases: ["dc"]
    permission: mario.discord
  setlink:
    description: Setzt den Link für /discord
    aliases: ["sl"]
    permission: mario.setlink
  fly:
    description: Fly Command
    permission: mario.fly
  dumb:
    description: Du bist dumm
    aliases: ["dumm"]
    permission: mario.dumb
  chatclear:
    description: Cleart den Chat
    aliases: ["cc"]
    permission: mario.chatclear
  clearinventory:
    description: Cleart dein Inventar
    aliases: ["clearinv", "cleari", "ci"]
    permission: mario.clear
  gm:
    description: Ist wie /gamemode nur in kurz
    permission: mario.gm
  nick:
    description: Nickt dich
    permission: mario.nick
  unnick:
    description: Unnickt dich
    permission: mario.unnick
  day:
    description: Macht Tag
    permission: mario.day
  night:
    description: Macht Nacht
    permission: mario.night
  timer:
    description: Einfacher Timer Command
    permission: mario.timer
  speed:
    description: Gibt dir Speed
    permission: mario.speed
  realname:
    description: Gibt dir den echten Namen eines genickten Spielers
    permission: mario.realname
  backpack:
    description: Öffnet ein personalisiertes Backpack!
    aliases: ["bp"]
    permission: mario.backpack
  enderchest:
    description: Öffnet die persönliche Enderchest!
    aliases: ["ec"]
    permission: mario.ec
  invsee:
    description: Öffnet das Inventar eines anderen Spielers!
    aliases: ["isee"]
    permission: mario.invsee
  enderinvsee:
    description: Öffnet die Enderchest eines anderen Spielers!
    aliases: ["esee"]
    permission: mario.enderinvsee
  kickall:
    description: Kickt alle Spieler, die Online sind, außer den Commandsender!
    aliases: ["ka"]
    permission: mario.kickall
  banall:
    description: Bannt alle Spieler, die Online sind, außer der Commandsender!
    aliases: [ "ba" ]
    permission: mario.banall
  backpacklarge:
    description: Öffnet ein personalisiertes Backpack mit der Größe einer Doppelkiste!
    aliases: [ "bpl" ]
    permission: mario.backpacklarge
  sendactionbar:
    description: Sende eine "ActionBar" mit einer beliebigen Nachricht an einen Spieler!
    aliases: [ "sab" ]
    permission: mario.sendactionbar
  sendmessage:
    description: Sende eine Nachricht an einen Spieler!
    aliases: [ "sm" ]
    permission: mario.sendmessage
  sendtitle:
    description: Sende einen Titel mit einer beliebigen Nachricht an einen Spieler!
    aliases: [ "st" ]
    permission: mario.sendtitle
  clearenderchest:
    description: Cleart deine Ender Chest
    aliases: [ "clearec", "cec" ]
    permission: mario.clearenderchest
  backpackstored:
    description: Siehe in ein gelagertes Backpack eines Spielers!
    aliases: [ "bps" ]
    permission: mario.backpackstored
  restoreinventory:
    description: Gebe einen Spieler das gelagerte Inventar zurück! BETA
    aliases: [ "riv", "reinv", "rinv" ]
    permission: mario.restoreinventory
  storeinventory:
    description: Lager das Inventar eines Spielers! BETA
    aliases: [ "siv", "stinv", "sinv" ]
    permission: mario.storeinventory
  troll:
    description: Trolle jemandem mit einem Explosions Paket haha
    permission: mario.troll
  sign:
    description: Signiert ein Item in deiner Hand!
    permission: mario.sign
  worldtp:
    description: Teleportiere dich in eine Welt!
    aliases: [ "wtp" ]
    permission: mario.worldtp
  worldcreate:
    description: Erstelle eine Welt!
    aliases: [ "wc" ]
    permission: mario.worldcreate

permissions:
  mario.*:
    description: Alle Rechte zu diesem Plugin!
    children:
      mario.reload: true
      mario.stop: true
      mario.restart: true
      mario.date: true
      mario.lol: true
      mario.heal: true
      mario.kick: true
      mario.die: true
      mario.broadcast: true
      mario.broadcast5: true
      mario.discord: true
      mario.setlink: true
      mario.fly: true
      mario.dumb: true
      mario.chatclear: true
      mario.clear: true
      mario.gm: true
      mario.nick: true
      mario.unnick: true
      mario.day: true
      mario.night: true
      mario.timer: true
      mario.speed: true
      mario.realname: true
      mario.backpack: true
      mario.ec: true
      mario.invsee: true
      mario.enderinvsee: true
      mario.kickall: true
      mario.banall: true
      mario.backpacklarge: true
      mario.sendactionbar: true
      mario.sendmessage: true
      mario.sendtitle: true
      mario.clearenderchest: true
      mario.backpackstored: true
      mario.restoreinventory: true
      mario.storeinventory: true
      mario.troll: true
      mario.sign: true
      mario.worldtp: true
      mario.worldcreate: true
  mario.heal:
    description: Damit kannst du dich heilen.
    default: op
    children:
      mario.heal.other:
        description: Rechte, um andere zu heilen!
        default: op
  mario.reload:
    description: Rechte für den /announcereload Command!
    default: op
  mario.stop:
    description: Rechte für den /announcestop Command!
    default: op
  mario.restart:
    description: Rechte für den /announcerestart Command!
    default: op
  mario.kick:
    description: Rechte für den /announcekick Command!
    default: op
  mario.lol:
    description: Rechte für den /lol Command!
    default: op
  mario.date:
    description: Rechte für den /date Command!
    default: op
  mario.die:
    description: Rechte für den /die Command!
    default: op
  mario.broadcast:
    description: Rechte für den /broadcast Command!
    default: op
  mario.broadcast5:
    description: Rechte für den /broadcast5 Command!
    default: op
  mario.discord:
    description: Rechte für den /discord Command!
    default: op
  mario.setlink:
    description: Rechte für den /setlink Command!
    default: op
  mario.fly:
    description: Rechte für den /fly Command!
    default: op
  mario.dumb:
    description: Rechte für den /dumb Command!
    default: op
  mario.chatclear:
    description: Rechte für den /chatclear Command!
    default: op
  mario.clear:
    description: Rechte für den /clearinventory Command!
    default: op
  mario.gm:
    description: Rechte für den /gm Command!
    default: op
  mario.nick:
    description: Rechte für den /nick Command!
    default: op
  mario.unnick:
    description: Rechte für den /unnick Command!
    default: op
  mario.day:
    description: Rechte für den /day Command!
    default: op
  mario.night:
    description: Rechte für den /night Command!
    default: op
  mario.timer:
    description: Rechte für den /timer Command!
    default: op
  mario.speed:
    description: Rechte für den /speed Command!
    default: op
  mario.realname:
    description: Rechte für den /realname Command!
    default: op
  mario.backpack:
    description: Rechte für den /backpack Command!
    default: op
  mario.ec:
    description: Rechte für den /enderchest Command!
    default: op
  mario.invsee:
    description: Rechte für den /invsee Command!
    default: op
  mario.enderinvsee:
    description: Rechte für den /enderinvsee Command!
    default: op
  mario.kickall:
    description: Rechte für den /kickall Command!
    default: op
  mario.banall:
    description: Rechte für den /banall Command!
    default: op
  mario.backpacklarge:
    description: Rechte für den /backpacklarge Command!
    default: op
  mario.sendactionbar:
    description: Rechte für den /sendactionbar Command!
    default: op
  mario.sendmessage:
    description: Rechte für den /sendmessage Command!
    default: op
  mario.sendtitle:
    description: Rechte für den /sendtitle Command!
    default: op
  mario.clearenderchest:
    description: Rechte für den /clearenderchest Command!
    default: op
  mario.backpackstored:
    description: Rechte für den /backpackstored Command!
    default: op
  mario.restoreinventory:
    description: Rechte für den /restoreinventory Command!
    default: op
  mario.storeinventory:
    description: Rechte für den /storeinventory Command!
    default: op
  mario.troll:
    description: Rechte für den /troll Command!
    default: op
  mario.sign:
    description: Rechte für den /sign Command!
    default: op
  mario.worldtp:
    description: Rechte für den /worldtp Command!
    default: op
  mario.worldcreate:
    description: Rechte für den /worldcreate Command!
    default: op